version: '3'
networks:
  net:
    driver: bridge
volumes:
  cache:
    driver: local
services:
  power-watcher:
    build: .
    restart: always
    depends_on:
      - cache
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - CHAT_ID_TO_REPORT=${CHAT_ID_TO_REPORT}
      - ADMIN_USER_ID=${ADMIN_USER_ID}
      - REDIS_ADDRESS=redis://cache
    networks:
      - net
  cache:
    image: redis:alpine
    restart: always
    networks:
      - net
    command: redis-server --save 60 1
    volumes: 
      - cache:/data
